name: Release Pipeline

on:
  push:
    # run only against tags
    tags:
      - "*"

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ${{ matrix.host.os }}
    strategy:
      matrix:
        host:
          - os: ubuntu-latest
            goos: linux
          - os: macos-latest
            goos: darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.3

      - name: Install dependencies
        run: |
          if [ "${{ matrix.host.os }}" == "ubuntu-latest" ]; then
            sudo apt-get update -y
            sudo apt-get install -y gcc-aarch64-linux-gnu
          elif [ "${{ matrix.host.os }}" == "macos-latest" ]; then
            brew install coreutils
          fi

          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "v2.1.0"
          args: release --clean --parallelism=1 --config=.goreleaser-${{ matrix.host.goos }}.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
